// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzJ6CiOclKOXogo5ib7MhrcPgbFdvoE9I',
    appId: '1:775061915012:web:f26149a4a94a87bd41c9d1',
    messagingSenderId: '775061915012',
    projectId: 'lufick-project',
    authDomain: 'lufick-project.firebaseapp.com',
    storageBucket: 'lufick-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxy_NTLunkKWbwmZjNQREAzPKJiBzzO9M',
    appId: '1:775061915012:android:be7230464d64425341c9d1',
    messagingSenderId: '775061915012',
    projectId: 'lufick-project',
    storageBucket: 'lufick-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIrFgyW5Ng8WbG8s0E2zAe-uByN6DmduQ',
    appId: '1:775061915012:ios:057417287137b5f041c9d1',
    messagingSenderId: '775061915012',
    projectId: 'lufick-project',
    storageBucket: 'lufick-project.firebasestorage.app',
    iosBundleId: 'com.example.authenticationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIrFgyW5Ng8WbG8s0E2zAe-uByN6DmduQ',
    appId: '1:775061915012:ios:057417287137b5f041c9d1',
    messagingSenderId: '775061915012',
    projectId: 'lufick-project',
    storageBucket: 'lufick-project.firebasestorage.app',
    iosBundleId: 'com.example.authenticationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzJ6CiOclKOXogo5ib7MhrcPgbFdvoE9I',
    appId: '1:775061915012:web:6f6e54f0fbcec73e41c9d1',
    messagingSenderId: '775061915012',
    projectId: 'lufick-project',
    authDomain: 'lufick-project.firebaseapp.com',
    storageBucket: 'lufick-project.firebasestorage.app',
  );
}
